### ISSUE TITLE
Errors when using 'cache' property on client config options

### ISSUE THREAD

**Issue by papertokyo** [nuxt-community/apollo-module#121] opened 2018-07-04 19:18 UTC
### Version

[v4.0.0-beta.5](https://github.com/apollo-module/releases/tag/v4.0.0-beta.5)

### Reproduction link

[https://github.com/papertokyo/apollo-module-error](https://github.com/papertokyo/apollo-module-error)

### Steps to reproduce

On project with apollo module, add 'cache' property to default client using result from apollo-cache-inmemory generator
Run dev
Open index page in browser

### What is expected ?

Apollo client is configured with custom cache object

### What is actually happening?

Build fails with TypeError
"client.cache.extract is not a function"

### Additional comments?

I have a graphQL schema with multiple sub field fragments, which apparently requires the IntrospectionFragmentMatcher from apollo.

https://www.apollographql.com/docs/react/advanced/fragments.html#fragment-matcher

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c104">#c104</a>)</em></sub></div>

**Comment by dohomi** [comment] 2018-07-05 00:49
duplicate of #120

**Closed by dohomi** 2018-07-05 00:49 UTC
Labels: cmty:bug-report
