### ISSUE TITLE
Cannot read property 'extract' of undefined

### ISSUE THREAD

**Issue by aldarund** [nuxt-community/apollo-module#111] opened 2018-06-11 14:16 UTC
### Version

[v4.0.0-beta.1](https://github.com/apollo-module/releases/tag/v4.0.0-beta.1)

### Reproduction link

[-](-)

### Steps to reproduce

I tried to update my project to 4.0.0-beta.1 from 3.0.7.
Changed my config from a js file to
```
  apollo: {
    tokenName: 'JWT',
    clientConfigs: {
      default: {
        httpEndpoint: 'http://localhost'
      }
    }
  },
```
And now it just throws a error and i cant even find where from its coming...

```
[16:05:58] TypeError: Cannot read property 'extract' of undefined
at ApolloProvider.getStates (C:\Dev\PycharmProjects\rasimplefront\ra-front-simple-nu\node_modules\vue-apollo\dist\vue-apollo.umd.js:1456:34)
at beforeNuxtRender (.nuxt/apollo-module.js:70:0)
at process._tickCallback (internal/process/next_tick.js:68:7)
```

### What is expected ?

no error

### What is actually happening?

error

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c91">#c91</a>)</em></sub></div>

**Comment by dohomi** [comment] 2018-06-12 00:09
@aldarund is it possible that the endpoint is not running? I haven't faced your issue yet - is it possible that you wire up a reproduction?

**Comment by aldarund** [comment] 2018-06-12 00:22
@dohomi no, it dont even hit endpoints. I dont even know where it happens because it just happens on loading my index page. And i dont do anything on index page with apollo. I though it was my auth calls but when i disabled it nothing really changed. The only place where they was left was in vuex store, but they wasnt actually called at index page.
I tried to reproduce it on new repo but it doesnt happen.
What is bugging me is that stacktrace starts at next_tick, so i cant trace where from this error coming originally. Reverting to 3.0.7 made it work like it was.
I`l try to dig more into it tomorrow. If you have any ideas where i should look let me know please :)

**Comment by dohomi** [comment] 2018-06-12 00:29
So basically the big change of v4 is that we utilize https://github.com/Akryum/vue-cli-plugin-apollo/blob/master/graphql-client/src/index.js and so you only need to pass in a valid endpoint. if you have a debugger maybe check the console log in this file: https://github.com/nuxt-community/apollo-module/blob/master/lib/templates/plugin.js#L68

make sure that the initialization of apolloProvider works as expected. For me it looks like that your endpoint is not ready thus the init would fail

**Comment by aldarund** [comment] 2018-06-12 10:45
endpoint is a totally separate server that is started before nuxt, so thats shouldnt be a problem.
I found a problem.
In not working case apollo-client is 1.9.3
In working case apollo-client is 2.3.2
I dont have apollo-client in my package.json. But i do have serverless.
So to reproduce issue just need
```yarn add serverless --dev```
And it will lead to apollo-client 1.9.3 used instead of 2.3.2

**Comment by dohomi** [comment] 2018-06-12 13:18
@aldarund as the docs stated you must use apollo v2.x. Probably just run your own version of apollo-client with yarn add apollo-client on the server. Will close it here as its not connected to apollo-module - thanks for reporting back

**Closed by dohomi** 2018-06-12 13:18 UTC
Labels: cmty:bug-report
