### ISSUE TITLE
Apollo client hydration

### ISSUE THREAD

**Issue by yaki4** [nuxt-community/apollo-module#200] opened 2019-02-15 16:02 UTC
### Version

[v4.0.0-rc.4](https://github.com/apollo-module/releases/tag/v4.0.0-rc.4)

### Reproduction link

[https://graphnewreader-uqpacjfhny.now.sh](https://graphnewreader-uqpacjfhny.now.sh)

### Steps to reproduce

Click one of the link for second page. 
Click the second button.
New query load.

link to git: https://gitlab.com/yaki4/grapheader.git

### What is expected ?

New query use new store value in headers.

### What is actually happening?

New query doesn't use new store value in headers.

### Additional comments?

I already fill a bug report for this one. But the update doesn't resolve this issue. 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c182">#c182</a>)</em></sub></div>

**Comment by yaki4** [comment] 2019-03-01 14:50
I've find an alternative in case someone is interested. 
You can use the link option in your client instead of the defaultHttpLink option. 
All you have to do is add apollo-link-http to you project and then you can create a middlewareLink like so : 
`export default ({req, app}) => {
    const endpoint = 'https://mysuperbgraphql/api/queries'
    let httpLink = new HttpLink({ uri: endpoint, credentials: 'include'})
    const middlewareLink = new ApolloLink((operation, forward) => { 
        let headersVal = {
            'Accept-Language': app.i18n.locale
        }
        const source = process.server ? req.headers.cookie : document.cookie
        if (source) {
            const parsecookie = cookieparser.parse(source)
            if (parsecookie.authorization) {
                // pass auth token in headers
                headersVal['Authorization'] = parsecookie.authorization
            }
        }
        operation.setContext({
            headers: headersVal,
            uri: endpoint,
            credentials: 'include'
        })
        return forward(operation)
    })
    const link = middlewareLink.concat(httpLink)
    return {
        defaultHttpLink: false,
        link: link,
        cache: new InMemoryCache()
    }
}`

Although, i think that the default client should be able to detect the changed value by himself. For example if you use i18n value in your client for custom endpoint for example. The client has to be dynamic. 
But maybe i'm wrong and there is no other way than use a middlewareLink to detect this changes.

**Comment by AleksejDix** [comment] 2019-03-04 14:36
You can see this bug happening live on this website https://webzueri.ch/

**Comment by AleksejDix** [comment] 2019-03-05 08:29
Here is a Repository with bug reproduction
https://github.com/AleksejDix/Bug-nuxt-apollo-apollo-nuxt-module

**Comment by dhritzkiv** [comment] 2019-03-06 22:44
@AleksejDix if you pin your vue version to 2.6.7 (instead of 2.6.8) and nuxt to 2.4.3, does this still happen?

I get this issue in nuxt (nuxt-ts, more specifically) v2.4.8 and vue v2.6.8, but not in the older version.

**Comment by sh** [comment] 2019-03-07 02:49
I'm having the same issue with nuxt-edge, v2.4.5 is the last release that worked.

as @dhritzkiv mentioned, the update from vue 2.6.7 to 2.6.8 in https://github.com/nuxt/nuxt.js/pull/5122 introduced the issue

**Comment by sh** [comment] 2019-03-07 03:08
it's actually `@nuxt/devalue@1.2.1` that introduced the bug, the related PR is: https://github.com/nuxt/devalue/pull/6

**Comment by aldarund** [comment] 2019-03-07 12:53
@AleksejDix thanks for reproduction, i have created a fix https://github.com/nuxt/devalue/pull/7

**Comment by rnenjoy** [comment] 2019-03-12 13:11
Is it possible for me to use that fix somehow before the actual release? I'm getting error on all pages about missmatched Nodes

**Comment by dhritzkiv** [comment] 2019-03-25 22:13
Seems to be fixed in the latest Nuxt + vue

**Closed** 2019-04-17 18:48 UTC
Labels: cmty:bug-report
